### ISSUE TITLE
CSS Properties color

### ISSUE THREAD

**Issue by enkia** [zaynali53/acme-color-scheme#1]
I absolutely love this color scheme but I had to change the color of the CSS properties to something ever so slightly lighter. (#696c7d)

Many people keep the brightness of their monitor fairly low so take that into consideration.

**Comment by zaynali53** [comment]
@enkia Thanks. I was also thinking the same :) 

I was going to update the css properties highlight and this is what i come up with. `#717486`. 
Also this color is from the color palette too.

![capture](https://cloud.githubusercontent.com/assets/8646770/16275129/2bbe86e8-38c2-11e6-8cbb-efaa0e862920.PNG)

**Comment by enkia** [comment]
Perfect!

**Comment by zaynali53** [comment]
@enkia Fixed https://github.com/zaynali53/acme-color-scheme/commit/d6c71ba26f437082e8d09a31469d6faa132d9e05
